pkg/src/string_hash_code.c
Verfied with R 3.0.0. Built passed and PI example can run.
=> [SPARKR-165] IS_SCALAR is not present in R before 3.1

pkg/R/sparkR.R, pkg/R/sparkRBackend.R
This change has two fixes
1. When the workspace is saved (from R or RStudio) the backend connection seems to be closed before the finalizer is run. In such cases we reopen the connection and stop the backend
2. With RStudio when R is restarted, there are port-conflicts which appear due to a race condition between the JVM and rsession restart. This change adds a 1 sec sleep to avoid this race.
cc @piccolbo
=> [SPARKR-185] Fix SparkR backend to exit in more cases

pkg/R/sparkRBackend.R
Construct the whole request message to send it once, avoiding write-write-read pattern in case of Nagle's algorithm.
=> [SPARKR-183] Fix the issue that parallelize collect tests are slow.

pkg/R/RDD.R, pkg/inst/tests/test_textFile.R
When creating a pipeline RDD, we need to check if the JavaRDD belonging to the parent is serialized.
Added a test case based on the JIRA 
cc @concretevitamin
=> [SPARKR-140] Fix serialization tracking in pipelined RDDs

pkg/src/build.sbt, pkg/src/pom.xml
This fixes builds using Spark 1.2 inheriting the wrong hadoop-client version (especially with SBT).
Before this fix if you ran `SPARK_VERSION=1.2.0 ./install-dev.sh` you would see `hadoop-client-2.2.0` being included even though our hadoop-client version is set to 1.0.4. This is because spark-core depends on Hadoop Client 2.2.0 http://mvnrepository.com/artifact/org.apache.spark/spark-core_2.10/1.2.0
=> Exclude hadoop client from Spark dependency

pkg/R/sparkR.R, pkg/R/sparkRClient.R
This PR fixes a couple of problems reported by users on Windows
- The first fix is to make the classpath separator `;` as described in [1]
- The second fix is to handle spaces in the install path (in Windows, Unix-like platforms). The solution that seems to work across all platforms is to convert the jar paths to URIs and encode the URIs using `URLEncode`
Tested on Mac, Windows VM and Linux VM. P.S: Reviewers might find it useful to test using something like
```
library(devtools)
with_lib("/tmp/sparkr install", install_github(repo = "shivaram/SparkR-pkg/pkg@windows-space-fix"))
```
[1] http://stackoverflow.com/a/4528456/4577954
=> [SPARKR-200][SPARKR-149] Fix path, classpath separator for Windows

pkg/R/RDD.R, pkg/R/pairRDD.R
Replace the `rdd` argument in all of the S4 methods with `x`. This will allow us to standardize the code as other Spark components get added and we need to set up multiple dispatch on S4 methods.
In any cases where `x` was used as a generic iterator, I've replaced it with `i` except in a few cases where a different letter made sense. For example, in some of the pair functions, we now use `function(k)` and `function(v)` for the key/value functions.
=> Update method signatures to use generic arg

pkg/inst/worker/worker.R, pkg/src/src/main/scala/edu/berkeley/cs/amplab/sparkr/RRDD.scala
This PR will use socket to send and receive result from R worker. 
The reason we can not use stdin/stdout is that we plan to have daemon to launch the R worker,  then the stdin/stdout can not accessible from JVM.
=> [SPARKR-155] use socket in R worker

pkg/NAMESPACE, pkg/R/DataFrame.R, pkg/R/utils.R, pkg/inst/tests/test_sparkSQL.R
- `repartition`
- `distinct`
- `sampleDF`
`sampleDF` currently only uses the random seed version. It seems that in order to be able to set the seed manually, we'll need to be able to pass a Long type through `callJMethod` first. That can be expanded later unless someone already has it figured out.
=> Three more DataFrame methods

pkg/src/src/main/scala/edu/berkeley/cs/amplab/sparkr/RRDD.scala
Calling `redirectErrorStream` without any arguments only tests whether stderr is redirected to stdout. JavaDoc at http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#redirectErrorStream() explains this
cc @davies
=> Fix stderr redirection on executors

pkg/R/column.R, pkg/inst/tests/test_sparkSQL.R, pkg/src/build.sbt
Updated column to use `functions` instead of `Dsl` in accordance with the new API changes.
Also created separate S4 generics for `asc` and `desc` since they're actual `Column` methods
=> New 1.3 repo and updates to `column.R`

pkg/NAMESPACE, pkg/R/DataFrame.R, pkg/R/column.R, pkg/R/pairRDD.R, pkg/inst/tests/test_sparkSQL.R
SQL-Like methods:
- `join`
- `sort`
- `orderBy`
- `filter`
- `where`
=> [SparkR-209] `join`, `sort`, `filter` methods for DataFrame

pkg/src/src/main/scala/edu/berkeley/cs/amplab/sparkr/SparkRBackendHandler.scala
This print statement is noisy for SQL methods which have multiple APIs
(like loadDF). We already have a better error message when no valid
methods are found
cc @davies
=> Remove print statement in SparkRBackendHandler

pkg/inst/worker/daemon.R, pkg/inst/worker/worker.R, pkg/src/src/main/scala/edu/berkeley/cs/amplab/sparkr/RRDD.scala, pkg/src/src/main/scala/edu/berkeley/cs/amplab/sparkr/SerDe.scala
The Spark executor could use lots of memory to cache some data, then it's very expensive to fork a R process (or easy to fail).
The solution is fork a lightweight daemon (in R) process in the beginning (when needed), call the daemon to launch R worker when needed.
This is only works in Linux/Mac, In Windows, it will still fork a R worker from JVM.
This also reduce the overhead to launch a task from about 350ms to 30ms (tested on Mac OS X 10.9)
TODO: improve failure handling. (delay it until we finalize the code for worker)
=> [SPARKR-214] launch R worker by a daemon

pkg/R/SQLContext.R, pkg/inst/tests/test_sparkSQL.R
This is a simple fix to make parquetFile work in R. See https://sparkr.atlassian.net/browse/SPARKR-208 for details.
=> [SPARKR-208] Changed SQLContext.R#parquetFile signature to match the java version

sparkR
Before this change calling `head` on a DataFrame would not
work from the sparkR script as utils would be loaded after SparkR
and placed ahead in the search list. This change requires utils to
be loaded before SparkR
To test this you can try something like the following with and without this change
```
./sparkR
>mockLines <- c("{\"name\":\"Michael\"}",
"{\"name\":\"Andy\", \"age\":30}",
"{\"name\":\"Justin\", \"age\":19}")
>jsonPath <- tempfile(pattern="sparkr-test", fileext=".tmp")
>writeLines(mockLines, jsonPath)
>df <- jsonFile(sqlCtx, jsonPath)
>head(df)
```
cc @davies
=> Include utils before SparkR for `head` to work

pkg/R/utils.R, pkg/inst/tests/test_utils.R
1. Grouped several test cases together to condense the test code. Added test for def-use chain with interleaving function calls, and recursive function calls. 
2. Fixed the issue with recursive function calls, which led to infinite recursion.
3. Replace global `defVars` (holding the local var names) with local one to `cleanClosure()`. The previous version will clear the `defVars` once `processClosure()` calls cleanClosure() on processing functions. (https://github.com/amplab-extras/SparkR-pkg/blob/master/pkg/R/utils.R#L312)
=> Fix cleanClosure() on recursive function calls.

pkg/R/broadcast.R, pkg/R/jobj.R, pkg/R/serialize.R, pkg/R/sparkR.R, pkg/R/sparkRBackend.R, pkg/inst/tests/test_context.R
This fixes the problem where unit tests could not shutdown SparkContext. Also to help users debug such problems associate a JVM id for each JVM reference we hold. The validity of this id is also checked before a JVM reference is passed to the backend.
cc @davies
=> [SPARKR-219] Clear broadcast variables when JVM is shutdown

pkg/inst/tests/test_binary_function.R
The issue reported in https://sparkr.atlassian.net/browse/SPARKR-224 was fixed by https://sparkr.atlassian.net/browse/SPARKR-228. Here I add a new test case to unionRDD(), which helped to catch the issue.
=> [SPARKR-224] The serialized flag in a PipelinedRDD is not set correctly.

index.html
We might want to link to the JIRA, but this comment should at least make new developers aware that things are changing. The new github repo at apache Spark should contain any new information as it becomes available. Linking to the JIRA conversation doesn't seem necessary.
=> added warning on new spark release

README.md
a similar pull request was made for the github pages. i've added the same warning to the readme.md file as well. some people (like me) skip the website and go straight for the github. might be fair to add a warning here as well.
=> warning on spark 1.4 in readme.md 

pkg/src/sbt/sbt
For the installation of SparkR, I changed the sbt configuration.
These changes are based on the suggestions here: https://github.com/databricks/spark-csv/issues/114
Now fetching the file 'sbt-launch-0.13.6.jar' works.
And installation of SparkR works.
Maybe this could be useful for your repo?
Cheers,
Thorben
=> fixed sbt config
